### ISSUE TITLE
Simulator: Cope with RSS feeds containing only 1 item

### ISSUE THREAD

**Issue by duncanmortimer** [oakling/akorn.scrapers#4]
Currently, the simulator displays a 'sample larger than population' message when presented with an RSS feed with fewer than 2 items.

Perhaps when the feed has a single item, it could process and display that item?

**Comment by craigloftus** [comment]
Would you be able to provide an example of such a feed, so I can test?

**Comment by duncanmortimer** [comment]
Hi Craig --- should have done that, sorry.

http://metadata.osa.org/rss/infobase/aop_feed.xml

**Comment by craigloftus** [comment]
Resolved in https://github.com/oakling/Oakling/commit/f61ea540b1.
