### ISSUE TITLE
Simulator: Supply article URL as well as feed URL

### ISSUE THREAD

**Issue by duncanmortimer** [oakling/akorn.scrapers#5]
When developing a scraper, it would be useful to be able to try the scraper repeatedly on the same article URL, rather than just the feed URL.

**Comment by craigloftus** [comment]
Resolved in https://github.com/oakling/Oakling/commit/f61ea540b1.

Within the "Preview" pane, use the refresh button next to the URL of the article you want to repeat. This will use a cached version of the page.

It is not tremendously intuitive, but doing it 'properly' would have required quite a lot of refactoring.
